# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-03 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='model',
            field=models.CharField(default='d3', max_length=50),
            preserve_default=False,
        ),
    ]
