# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-04 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_detail_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='model',
        ),
        migrations.AlterField(
            model_name='detail',
            name='car',
            field=models.CharField(max_length=100),
        ),
    ]
