# Generated by Django 2.0.1 on 2018-01-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20180104_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='price',
            field=models.CharField(max_length=30),
        ),
    ]
