# Generated by Django 2.0.1 on 2018-01-18 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20180117_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='type_of_detail',
        ),
    ]
