# Generated by Django 2.0.1 on 2018-01-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20180119_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='img',
        ),
        migrations.AddField(
            model_name='detail',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='details'),
        ),
    ]
