# Generated by Django 2.0.1 on 2018-01-19 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20180119_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='author',
        ),
    ]
