# Generated by Django 2.0.1 on 2018-01-20 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_detail_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='details')),
            ],
        ),
        migrations.RemoveField(
            model_name='detail',
            name='images',
        ),
        migrations.AlterField(
            model_name='detail',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='shop.Detail'),
        ),
    ]
