# Generated by Django 2.0.1 on 2018-01-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20180120_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='detail',
        ),
        migrations.AddField(
            model_name='detail',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='details'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
