# Generated by Django 2.0.1 on 2018-01-20 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20180120_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='details')),
            ],
        ),
        migrations.RemoveField(
            model_name='detail',
            name='images',
        ),
        migrations.AddField(
            model_name='detailimage',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.Detail'),
        ),
    ]
