# Generated by Django 2.0.1 on 2018-01-20 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_detail_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='author',
        ),
    ]
