# Generated by Django 2.0.1 on 2018-02-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_remove_detail_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='deleted',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
