# Generated by Django 2.0.1 on 2018-02-02 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_detail_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='deleted',
        ),
    ]
